file_handlers:
  yaml: loren.parsers.yaml_parser.YamlParser
  yml: loren.parsers.yaml_parser.YamlParser
  json: loren.parsers.json_parser.JSONParser
  py: loren.parsers.python_parser.PyParser
  csv: loren.parsers.csv_parser.CSVParser
  tsv: loren.parsers.csv_parser.TSVParser
  j2: loren.parsers.jinja2_parser.Jinja2Parser
  jinja2: loren.parsers.jinja2_parser.Jinja2Parser
  "*": loren.parsers.text_parser.TextParser
ignore:
  - .loren.yml
  - .DS_Store
  - _*
  - .*
  - templates*